[tool.poetry]
name = "magic-tiler"
version = "0.1.0"
description = ""
authors = ["abstractlyZach <zach3lee@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
i3ipc = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
